import os

print("TEXT_EMBEDDING_MODEL_DEPLOYMENT:", os.environ.get("TEXT_EMBEDDING_MODEL_DEPLOYMENT"))
print("AZURE_OPENAI_APIKEY:", os.environ.get("AZURE_OPENAI_APIKEY"))
print("AZURE_AI_SEARCH_API_KEY:", os.environ.get("AZURE_AI_SEARCH_API_KEY"))
print("AZURE_AI_SEARCH_INDEX_NAME:", os.environ.get("AZURE_AI_SEARCH_INDEX_NAME"))
print("TEXT_EMBEDDING_MODEL_NAME:", os.environ.get("TEXT_EMBEDDING_MODEL_NAME"))